#pragma once
#include "Torus.hpp"
#include "Primitives.hpp"
#include "EngineClass.hpp"
#include "Window.hpp"
#include "Sphere.hpp"
#include "Lights.hpp"
#include "PointLight.hpp"
#include "DirectionalLight.hpp"